### ISSUE TITLE
Make "max x-axis ticks" logic more flexible

### ISSUE THREAD

**Issue by daanlouter** [kiln/template-line-chart-race#118]
At the moment it sets an amount to the max amount of ticks, even if there's plenty of space available to show all the ticks.

<img width="1171" alt="screenshot 2018-11-19 at 12 07 54" src="https://user-images.githubusercontent.com/3636117/48706306-c5a05700-ebf3-11e8-8521-3c60f5bcde6f.png">

(this image shows only half of the ticks)

**Comment by keriley** [comment]
Just got a question about this on support, and yeah, it seems a bit odd to not be able to control the number of ticks or the interval.

**Comment by theduncanclark** [comment]
Note you can already control the number of ticks by just blanking the column headers!

**Comment by timbrock** [comment]
Got another user having this problem.
