### ISSUE TITLE
Add setting for label color

### ISSUE THREAD

**Issue by daanlouter** [kiln/template-line-chart-race#142]
In some cases using the line color is just very difficult to read.
<img width="131" alt="Screenshot 2019-04-30 at 13 11 46" src="https://user-images.githubusercontent.com/3636117/56960716-a7973500-6b49-11e9-9326-b86b23165d46.png">

**Comment by SarahSoutoul** [comment]
Done! https://github.com/kiln/template-line-chart-race/commit/f388c9c3a17966330bd687730f33e90389558b22
