### ISSUE TITLE
Chart overflowing if fixed_height is true and sizing mode is "Match data"

### ISSUE THREAD

**Issue by theduncanclark** [kiln/template-line-chart-race#146]
To repro, make a chart in the editor and set the height to be, say, 400px. In "Fill space" mode, this works fine. In "Auto" mode, however, it overflows. Presumably the correct behaviour is that if `fixed_height` is true, we should always be filling the available space.

**Comment by daanlouter** [comment]
I can't reproduce this with "Auto" mode, but can do when setting is set to "Match data". Will rename issue.
