### ISSUE TITLE
Improve aspect ratio options esp for mobile viewing

### ISSUE THREAD

**Issue by annaad22** [kiln/template-line-chart-race#157]
As requested by business customer here https://secure.helpscout.net/conversation/968151476/8377?folderId=2553237#thread-2723030846

**Comment by annaad22** [comment]
@daanlouter I think you also did this?

**Comment by daanlouter** [comment]
Yes, tagged the wrong issue. Done in https://github.com/kiln/template-line-chart-race/commit/190077443aeb495c1b26eb369738b6742fad91b9
