### ISSUE TITLE
Add option for margin between the y-axis values and the chart

### ISSUE THREAD

**Issue by annaad22** [kiln/template-line-chart-race#158]
![image](https://user-images.githubusercontent.com/46544749/65886515-658e4b80-e394-11e9-8edc-cd9910e06e51.png)

At the moment the distance is fixed and when the circle start radius is too large they are obscured.

Either lets have an option where you can set the margin, or let's set it automatically to allow enough space depending on the size of the start circle radius.

**Comment by theduncanclark** [comment]
This is included in the chart-layout module so would be added automatically if/when we drop that in.
