### ISSUE TITLE
x-axis labels not hidden in Edge / IE

### ISSUE THREAD

**Issue by annaad22** [kiln/template-line-chart-race#167]
bus customer. https://secure.helpscout.net/conversation/1006447157/10619/

In this chart the data is in 5 min intervals.
https://public.flourish.studio/visualisation/874306/

When viewing on Chrome some of the axis labels are hidden, to make the visualisation look good.

On Edge and IE all the labels are shown, which looks very squashed.

![lcr-fail-edge](https://user-images.githubusercontent.com/46544749/68933658-07bf9280-078d-11ea-9e8a-fb52ca2905e0.PNG)

**Comment by timbrock** [comment]
I suspect this is because IE/Edge don't support `getBoundingClientRect().x`.

**Comment by timbrock** [comment]
I suspected correctly.
