### ISSUE TITLE
Vertical margins ignored in header even when buttons present

### ISSUE THREAD

**Issue by timbrock** [kiln/template-line-chart-race#94]
Both this
<img width="1120" alt="screen shot 2018-05-08 at 12 06 41" src="https://user-images.githubusercontent.com/7906373/39753941-769bdd0c-52b8-11e8-8055-aaf7b5d187df.png">
and this
<img width="1119" alt="screen shot 2018-05-08 at 12 07 14" src="https://user-images.githubusercontent.com/7906373/39753942-76b17586-52b8-11e8-9bd3-2e317c857bef.png">
have the margin set at 80 pixels but in the latter case it is ignored vertically, even though the buttons form part of the header.

**Comment by daanlouter** [comment]
I believe this was fixed with layout module!
